name: Debug Pipeline

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - uses: actions/checkout@v3

      - name: Debug Info
        run: |
          echo "User:"
          whoami
          echo "Current Directory:"
          pwd
          echo "Files:"
          ls -la
          echo "Docker Version:"
          docker --version
          echo "Docker Compose:"
          docker-compose --version
          echo "Testing Docker:"
          docker ps
